### ISSUE TITLE
Page Template

### ISSUE THREAD

**Issue by martifenosa** [gridsome/gridsome-starter-wordpress#14]
Is there a way to use the template 'WordPressPage.vue' for most of the pages but have some of use a 'page.vue' file instead?

Maybe a file name based on the 'Default Template' or the assigned page template on the wordpress?

Thank's!

**Comment by hjvedvik** [comment]
You can try to use different layouts based on a property instead. Use a computed property in `WordPressPage.vue` which returns a component? Maybe something like this:

```html
<template>
  <component :is="layout">
    <div v-html="$page.wordPressPage.content" />
  </component>
</template>

<script>
import Layout from '~/layouts/Default.vue'
import AnotherLayout from '~/layouts/AnotherLayout.vue'

export default {
  computed: {
    layout () {
      switch (this.$page.wordPressPage.someProperty) {
        case 'another-layout' : return AnotherLayout
      }
      return Layout
    }
  }
}
</script>
```
