### ISSUE TITLE
Failed to make route like WordPress custom permalink 

### ISSUE THREAD

**Issue by mdobydullah** [gridsome/gridsome-starter-wordpress#18]
Thanks for making the starter template. I love this. 👍

But I've faced a problem. I've used custom permalink. That's the problem.

My WordPress site's slug with permalink: https://www.mynotepaper.com/laravel-login-event-listener.html

I tried to make like this. But it shows this error: <code>Cannot GET /laravel-cross-env-is-not-recognized-as-an-internal-or-external-command.html</code>

Here's the screenshot of my plugin setup:

![plugin config](https://user-images.githubusercontent.com/13184472/61581525-3f9d2d00-ab41-11e9-8fda-4183f2144dff.png)

Please help me to solve this. After solving this issue, I will able to build my site using Gridsome. Thank you.

**Comment by promovis** [comment]
Try updating Permalink Settings to the 2-nd option: "Day and name", as it will fit the post's route in gridsome.config
